---
name: "CITests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  citests:
    name: CI-Tests
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - name: Run cmake
        run: |
            CXXFLAGS="-Wall -Wextra -Wpedantic -Werror -g"
            CFLAGS="-Wall -Wextra -Wpedantic -Werror -g"
            cmake .
            make -j 4

      - name: Perform Unit Tests
        run: |
            ./ithitest

      - name: Run Valgrind
        run: |
            sudo apt-get install -y valgrind
            valgrind -v --error-exitcode=1  --track-origins=yes ./ithitest
            
      - name: Run Analysis
        run: |
             sudo apt-get install -y clang-tools
             mkdir analysis
             ( cd analysis
               echo "gitdir: ../.git" > .git
               git reset --hard
               scan-build cmake .
               mkdir -p /tmp/ithipages/analysis
               scan-build -o /tmp/ithipages/analysis --status-bugs make
             )
                   
      - name: Run Coverage
        run: |
             if [ ! -z "$encrypted_e845a59f36e1_key" -a ! -z "$encrypted_e845a59f36e1_iv" ] ; then
                geninfo .  -o ithitest.info
                lcov --remove ithitest.info '/usr/include/*' -o ithi.info
                mkdir -p /tmp/ithipages/coverage/master
                genhtml ithi.info --output-directory /tmp/ithipages/coverage/master
             fi
                   
      - name: Run Doxygen
        run: |
             doxygen travis/Doxyfile
                   
      - name: Post scripts
        run: |
             if [ ! -z "$encrypted_e845a59f36e1_key" -a ! -z "$encrypted_e845a59f36e1_iv" ] ; then
                 cp README.md /tmp/ithipages/README.md.orig
                ( cd /tmp/ithipages
                  ./mkreadme.sh && (
                   [ -d analysis ] && git add analysis
                   [ -d coverage ] && git add coverage
                   [ -d doxygen  ] && git add doxygen
                   git commit -a -m "update from travis at `date`" \
                   && git push
                   )
                )
             fi